### PR TITLE
Add systemd support

### PR DESCRIPTION
**Pull request by sharshenov**

### CODE REVIEW

**Comment by rqbanerjee** [comment]
this is rad. any chance you guys want to merge this and release a new gem? Ubuntu 16, which is probably the best base AMI on EC2, uses systemd instead of upstart now

**Comment by jgorset** [comment]
Sorry for never getting around to this! 😲

**Comment by jgorset** [comment]
I can't merge this because I'm not in @hyperoslo anymore, but maybe @timkurvers can?

**Comment by timkurvers** [comment]
Have given you admin rights on the repo again @jgorset ❤️  You're listed as the gem owner too, it seems.

**Comment by jgorset** [comment]
That works, too! Thanks @timkurvers.

**Comment by jgorset** [comment]
I'll add you to the list of gem owners, by the way.

**Comment by jgorset** [comment]
This is now v1.3.0 on Rubygems, @sharshenov and @rqbanerjee! Thanks! :sparkles: :cake: :sparkles:

**Pull request merged**
